language: node_js

node_js:
 - "0.10"
 - "0.8"
 - "0.6"

install:
 - npm install
 - npm install mocha
 - npm test

before_script:
 - make clean

script:
 - npm install --stage
 - npm test
 - sudo apt-get -qq install libsqlite3-dev
 - make clean
 - npm install --build-from-source --sqlite=/usr
 - ldd lib/binding/*/*/*node
 - npm test
