environment:
  node_pre_gyp_accessKeyId:
    secure: VVcArESQA6N2JeG/SkeMYVnHn5DMEuiwbsKHez3fzuA=
  node_pre_gyp_secretAccessKey:
    secure: 7lqDDrORt+VRTfVZh1ZcK5P3bAhFuiND9WmbDedehxLoqqdSiy8SBKWuKE2qVKyI
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10
    - nodejs_version: 0.11

platform:
  - x64
  - x86

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm --version
  - SET PATH=c:\python27;%PATH%
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - npm install --build-from-source  --msvs_version=2013
  - npm install mocha
  - npm test
  # add local node-pre-gyp dir to path
  - SET PATH=C:\projects\node-sqlite3\node_modules\node-pre-gyp\bin;%PATH%
  - node-pre-gyp package
  # make commit message env var shorter
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - if not "%CM%" == "%CM:[publish binary]=%" node-pre-gyp --msvs_version=2013 package publish 2>&1

artifacts:
  - path: build\stage
    name: BuildFiles

build: OFF
test: OFF
deploy: OFF
